export const organization = {
  name: 'Trinity Springs Christian Academy',
  established: '2023',
  campus: 'Shallow Well Church',
  street: '1220 Broadway Rd.',
  city: 'Sanford, NC 27332',
  mailingStreet: 'P.O. Box 204',
  mailingCity: 'Olivia, NC 28368',
  phone: '(910) 876-8952',
  phoneHref: 'tel:+19108768952',
  applicationEmail: 'info@TrinitySpringsNC.org',
  email: 'trinitysprings2023@gmail.com',
  facebook: 'https://www.facebook.com/share/wxMffPRkanvHWsNa/?mibextid=LQQJ4d',
  facebookLabel: '@TrinitySpringsChristianAcademy',
  instagram: 'https://www.instagram.com/trinitysprings23',
  instagramLabel: '@trinitysprings23',
  familiesFacebook: 'https://fb.me/g/4U7knbaNm/5RIAbu82',
  band: 'https://band.us/n/a0a0A0g4s96e0',
  landsEnd: 'https://www.landsend.com/co/account/school-uniforms?launchSearch=true',
  landsEndNumber: '900199464',
  dnpe: 'https://www.dnpesys.nc.gov/NPEPublic/default.aspx',
}
